"""Audit the legacy Knowledge_package/ against the rebuilt knowledge base (evidence for why it was replaced).

    python -m advisor.ingest.audit_legacy     -> knowledge_base/LEGACY_PACKAGE_AUDIT.md
"""
import json
import re
import sqlite3
from collections import defaultdict

from .. import config

LEGACY = config.ROOT / "Knowledge_package"
SHEET_BATCH = {"Sem Spread BTECH-2022": 2022, "Sem_Spread_2023": 2023, "Sem_Spread_2024": 2024, "Sem_Spread_2025": 2025, "Sem_Spread_DS_2026": 2026}


def load(name):
    return json.loads((LEGACY / name).read_text(encoding="utf-8"))


def main():
    con = sqlite3.connect(config.DB_PATH)
    con.row_factory = sqlite3.Row
    new = {(r["batch"], int(re.search(r"(\d+)$", r["cells"].split(":")[0]).group(1)), r["semester"]): dict(r)
           for r in con.execute("SELECT * FROM offerings")}
    old = {(SHEET_BATCH[r["sheet"]], r["source_row"], r["semester"]): r for r in load("02_semester_offerings.json")}
    code = lambda v: re.sub(r"\s+", "", v or "").upper()
    missing = sorted(k for k in new if k not in old)
    extra = sorted(k for k in old if k not in new)
    wrong = sorted(k for k in set(new) & set(old) if code(new[k]["code_raw"]) != code(old[k]["course_code"])
                   or (new[k]["C"] or 0) != (old[k]["credits"] or 0))
    per_sem = defaultdict(lambda: [0, 0])
    for k in new:
        per_sem[(k[0], k[2])][0] += 1
    for k in old:
        per_sem[(k[0], k[2])][1] += 1
    master = {c["course_code"] for c in load("01_course_master.json")}
    new_codes = {r["code"] for r in con.execute("SELECT code FROM options WHERE code_status='ok'")}
    struct_old = defaultdict(int)
    for r in load("03_curriculum_structure_courses.json"):
        struct_old[r["sheet"]] += 1
    struct_new = {r[0]: r[1] for r in con.execute("SELECT 'Struct_' || CASE batch WHEN 2026 THEN '2026_DS' ELSE batch END, count(*) FROM structure_courses GROUP BY batch")}
    docs = [json.loads(line) for line in open(LEGACY / "10_retrieval_documents.jsonl", encoding="utf-8")]
    no_batch = [d for d in docs if d["doc_type"] in ("semester_offering", "curriculum_structure") and not re.search(r"20(22|23|24|25|26)", d["text"])]
    conflicts_old = len(load("07_conflicts_and_variants.json"))
    issues_new = {r[0]: r[1] for r in con.execute("SELECT category, count(*) FROM issues GROUP BY category")}

    L = ["# Audit of the legacy `Knowledge_package/`", "",
         "Generated by `python -m advisor.ingest.audit_legacy` by diffing the legacy JSON against an independent re-extraction "
         "of the source workbooks (`knowledge_base/advisor.sqlite`, which passes all validation checks). The legacy "
         "`13_verification_report.json` claims PASS_WITH_CORRECTIONS; the findings below show it is not safe as ground truth, "
         "so it was kept for reference only and replaced by `knowledge_base/`.", "",
         "## 1. Semester offerings (`02_semester_offerings.json`)", "",
         f"- Source course cells: **{len(new)}**; legacy records: **{len(old)}**.",
         f"- Missing from legacy: **{len(missing)}**; present in legacy but not at that position in the source: **{len(extra)}**; "
         f"same position but different code/credits: **{len(wrong)}**.",
         "- The legacy records carry **no batch/year field** (only a sheet name), and none of its semester-offering retrieval texts names the batch.", "",
         "| Batch | Semester | Source cells | Legacy records |", "|---|---|---|---|"]
    L += [f"| {b} | {s} | {n} | {o}{' ⚠' if n != o else ''} |" for (b, s), (n, o) in sorted(per_sem.items()) if n != o or b == 2023]
    L += ["", "Mismatched cells (batch, sheet row, semester → source vs legacy):", ""]
    for k in wrong:
        L.append(f"- {k}: source `{code(new[k]['code_raw']) or new[k]['slot']}` ({new[k]['C']} cr) vs legacy `{old[k]['course_code']}` ({old[k]['credits']} cr)")
    L += ["", "Missing in legacy:", ""] + [f"- {k}: `{code(new[k]['code_raw']) or new[k]['slot']}` ({new[k]['C']} cr)" for k in missing]
    L += ["", "**Root cause:** in `Sem_Spread_2023` the semester 4-6 blocks have no 'Course Code' header, so a header-driven parser "
          "re-read the semester 3 block as semester 4 and skipped semesters 5 and 6. The rebuilt adapter uses the fixed block columns.", "",
          "## 2. Course master (`01_course_master.json`)", "",
          f"- Confirmed codes offered in the programme plans but absent from the legacy master: **{', '.join(sorted(new_codes - master)) or 'none'}**.",
          "- DATA207 and DATA303 are genuinely lost (the 2023 parsing bug and the `DATA 207` spacing). The others are alternatives inside "
          "paired cells (e.g. `MATH401/COMP401`, `PSYC101/ECON101`) that the legacy package kept as one unsplit string, so e.g. "
          "'Web Framework (COMP401)' or its L-T-P (2-0-4, written in the title) cannot be looked up individually.", "",
          "## 3. Curriculum structure (`03_curriculum_structure_courses.json`)", "", "| Sheet | Source rows | Legacy rows |", "|---|---|---|"]
    L += [f"| {s} | {struct_new.get(s, 0)} | {struct_old.get(s, 0)}{' ⚠' if struct_new.get(s, 0) != struct_old.get(s, 0) else ''} |" for s in sorted(struct_new)]
    L += ["", "The `Struct_2026_DS` **Electives** list (8 courses) is missing from the legacy package.", "",
          "## 4. Conflicts and data-quality coverage", "",
          f"- Legacy `07_conflicts_and_variants.json`: {conflicts_old} entries (title spellings and a few minor-course fields).",
          "- Rebuilt `issues` table: " + ", ".join(f"{k}: {v}" for k, v in sorted(issues_new.items())) + ".",
          "- Not flagged by the legacy package: prerequisites that exist nowhere (DATA206, COMP210, MATH131, ECON202, FINA201, MKMT201), "
          "prerequisites missing from or scheduled in the same semester of a batch plan, the 2026 basket Fixed-Min vs Struct disagreement, "
          "cross-batch changes of semester/credits/prerequisites, and the Handbook 75% vs 80% attendance conflict.", "",
          "## 5. Retrieval documents (`10_retrieval_documents.jsonl`)", "",
          f"- {len(docs)} documents; **{len(no_batch)}** semester-offering / curriculum-structure texts do not mention any batch year "
          "(e.g. \"Visualizing Data for Story Telling (DATA131) is listed in semester 1 under basket B2\"), so year-wise questions cannot be answered from them.",
          "- No Student Handbook or SOP content is included.", "",
          "## 6. What was correct", "",
          "- The 148 minor-course rows and the Struct 2022-2025 course lists match the source (placeholder rows such as TBA credits were dropped).", ""]
    (config.KB / "LEGACY_PACKAGE_AUDIT.md").write_text("\n".join(L), encoding="utf-8")
    print(f"missing={len(missing)} extra={len(extra)} wrong={len(wrong)} master_missing={sorted(new_codes - master)} no_batch_docs={len(no_batch)}")


if __name__ == "__main__":
    main()
